
services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: easytopup
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_service
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db

volumes:
  postgres_data:
